const enum ID {
    START_BUTTON = '__IDABOT_START_BUTTON__',
    INFO_BOX = '__IDABOT_MESSAGE_BOX__',
    CONTENT = '__IDABOT_CONTENT__',
    INFO_BOX_FOOTER = '__IDABOT_MESSAGE_BOX_FOOTER__',
    REFRESH_BUTTON = '__IDABOT_REFRESH_BUTTON__',
    PROGRESS_BAR = '__IDABOT_PROGRESS_BAR__',
}

export default ID;
